name: 'sops tools installer'
description: |-
  Install a specific version of the sops binary. Acceptable values are latest
  or any semantic version string like 0.31.0.
inputs:
  version:
    description: 'Version of sops'
    required: true
    default: 'latest'
outputs:
  path:
    description: 'Path to the cached sops binary'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: node24
  main: 'dist/index.js'
